---
- name: "apply basic role" 
  hosts: all
  become: true
  roles:
   - basics
  vars:
     users: provision

- name: "apply web server role"
  hosts: webservers
  become: true
  roles: 
   - webserver
