---
- hosts: 192.168.1.184
  become: True
  vars:
	NORMAL_USER_NAME: "{{ web }}"
 tasks: 
	- name: "Create a secondary, non-root user"
	  user: name={{ NORMAL_USER_NAME }}
		password='test'
		shell=/bin/bash
        home=/home/web
