---
- name: "Installing packages"
  apt: 
    name:
        - mysql-server
        - apache2
        - php
    state: present

- name: "Remove old httpd.conf"
  shell: creates=/etc/apache2/apache2.bak mv /etc/apache2/apache2.conf /etc/apache2/apache2.conf.bak

- name: "copy apache2 config"
  copy: src=../files/apache2.conf dest=/etc/apache2/apache2.conf owner=root group=root mode=0644
  notify:
     - restart-apache2-service

- name: "Remove old my.cnf"
  shell: creates=/etc/mysql/mysql.conf.d/mysqld.cnf.bak mv /etc/mysql/mysql.conf.d/mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf.bak

- name: "copy mysql config"
  copy: src=../files/mysqld.cnf dest=/etc/mysql/mysql.conf.d/mysqld.cnf owner=root group=mysql mode=0644
  notify: 
    - restart-mysql-service

